# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Patrick
subtitle:         'van Broeckhuijsen'
tagline:          ''
description:      'Mechatronics engineer by day.<br />Web developer by night.'
url:              https://patb.ro/
baseurl:          /

author:
  name:           'Patrick van Broeckhuijsen'
  url:            https://twitter.com/pvbroeckhuijsen

paginate: 5
paginate_path: "/blog/page:num/"

excerpt_separator: <!--more-->

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/patbro

sass:
  sass_dir: assets/css

plugins:
  - jekyll-paginate
  - jekyll-gist
  - redcarpet
